name: Deploy Tenant

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_tenant:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="tenant_name=${{ github.event.inputs.tenant_name }}"
